engines:
    eslint:
        enabled: true
        channel: eslint-3
    stylelint:
        enabled: true

ratings:
    paths:
        - "**/*.js"
        - "**/*.scss"

exclude_paths:
    - build/**/*
    - node_modules/**/*
