stages:
    - build
    - review

.build: &build-job
    stage: build
    cache:
        paths:
            - node_modules/
            #- $HOME/.yarn-cache
    artifacts:
        name: "${CI_BUILD_REF_NAME}-${CI_BUILD_NAME}"
        paths:
            - build/
            #- yarn.lock
    before_script:
        #- npm install yarn
    script:
        - npm install
        #- ./node_modules/.bin/yarn
        - ./node_modules/.bin/gulp init
        - ./node_modules/.bin/gulp build

build:node-6:
    image: node:6
    <<: *build-job

build:node-7:
    image: node:7
    <<: *build-job

sonar:
    image: maxwellewxam/sonar-scanner
    stage: review
    cache:
        paths:
            - .sonar/
    script: sonar-scanner \
      -Dsonar.host.url=http://sonar.flow.local:80 \
      -Dsonar.branch=$CI_BUILD_REF_NAME \
      -Dsonar.login=$SONAR_TOKEN \
      -Dsonar.analysis.mode=preview \
      -Dsonar.issuesReport.console.enable=true \
      -Dsonar.gitlab.commit_sha=$CI_BUILD_REF \
      -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME
