stages:
    - build
    - test
    - review


####################
# BUILD
####################
.build: &build-job
    stage: build
    cache:
        key: npm
        paths:
            - node_modules/
            #- $HOME/.yarn-cache
    before_script:
        #- npm -q install yarn
        #- ./node_modules/.bin/yarn
        - npm -q update
    script:
        - npm run build

build:node-6:
    image: node:6
    <<: *build-job
    artifacts:
        name: "${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
        paths:
            - build/
            #- yarn.lock
        expire_in: 1h

build:node-7:
    image: node:7
    allow_failure: true
    <<: *build-job


####################
# TEST
####################
test:
    image: node:6
    stage: test
    cache:
        key: npm
        paths:
            - node_modules/
    dependencies: []
    artifacts:
        name: "${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}_coverage"
        paths:
            - coverage/
        expire_in: 1h
    before_script:
        - npm -q update
    script: npm test

####################
# REVIEW
####################

# SonarQube
.sonarqube: &sonarqube-job
    image: maxwellewxam/sonar-scanner
    stage: review
    only:
        - branches
    cache:
        key: sonarqube
        untracked: true
        paths:
            - /root/.sonar/cache
    dependencies:
        - test
sonarqube:preview:
    <<: *sonarqube-job
    except:
        - master
        - dmz
    script: >
        sonar-scanner
        -D sonar.analysis.mode=preview
        -D sonar.host.url=$SONAR_HOST
        -D sonar.projectKey=$SONAR_PROJECT_KEY
        -D sonar.branch=$CI_COMMIT_REF_NAME
        -D sonar.login=$SONAR_TOKEN
        -D sonar.gitlab.project_id=$CI_PROJECT_PATH
        -D sonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -D sonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
sonarqube:
    <<: *sonarqube-job
    except:
        - dmz
    script: >
        sonar-scanner
        -D sonar.host.url=$SONAR_HOST
        -D sonar.projectKey=$SONAR_PROJECT_KEY
        -D sonar.branch=$CI_COMMIT_REF_NAME
        -D sonar.login=$SONAR_TOKEN

# Code Climate
#codeclimate:
#    image: node:6
#    stage: review
#    only:
#        - branches
#    except:
#        - dmz
#    dependencies:
#        - test
#    before_script:
#        - npm install -g codeclimate-test-reporter
#    script: codeclimate-test-reporter < coverage/lcov.info
