stages:
    - build
    - review

.build: &build-job
    stage: build
    cache:
        key: npm
        paths:
            - node_modules/
            - $HOME/.yarn-cache
    artifacts:
        name: "${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
        paths:
            - build/
            - yarn.lock
    before_script:
        - npm install yarn
    script:
        #- npm install
        - ./node_modules/.bin/yarn
        - npm run build

build:node-6:
    image: node:6
    <<: *build-job

build:node-7:
    image: node:7
    allow_failure: true
    <<: *build-job

sonar:
    image: maxwellewxam/sonar-scanner
    stage: review
    only:
        - branches
    except:
        - dmz
    cache:
        paths:
            - .sonar/
    script: >
        sonar-scanner
        -D sonar.host.url=$SONAR_HOST
        -D sonar.projectKey=$SONAR_PROJECT_KEY
        -D sonar.branch=$CI_COMMIT_REF_NAME
        -D sonar.login=$SONAR_TOKEN
        -D sonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -D sonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
