language: node_js
node_js:
  - 6
  - 7
matrix:
  allow_failures:
    - node_js: 7

addons:
  code_climate:
    repo_token: $CODECLIMATE_TOKEN

cache: yarn

script:
  - npm run build
  - npm test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
