language: node_js
node_js:
  - 6 # LTS NodeJS version.
  - 7 # Stable NodeJS version, optional.
matrix:
  allow_failures:
    - node_js: 7

addons:
  # Code Climate coverage reporting.
  code_climate:
    repo_token: $CODECLIMATE_TOKEN

cache: yarn

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm test
      after_success:
        # Code Climate coverage reporting.
        - npm install -g codeclimate-test-reporter
        - codeclimate-test-reporter < coverage/lcov.info
    - stage: review
      install: eslint eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard htmlhint pug-lint stylelint stylelint-config-standard stylelint-order stylelint-scss
      script: npm run lint
